// Angular/src/app/home/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { Products } from 'src/app/service/products.model';
import { ProductsService } from '../../service/products.service'
import { CartService } from 'src/app/service/cart.service';
// import { parse } from 'path';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.css']
})
export class ProductsComponent implements OnInit {

  products: Products[] = [];
  filter:any;

  

  constructor(private productsService: ProductsService, private cartService: CartService) { }
  ngOnInit() {
    this.productsService.readProducts().subscribe(pArr => {
      this.products = pArr.map(e => {
        return {
          id: e.payload.doc.id,
          ...e.payload.doc.data() as Products
        }
      })

    }) 
  };

  addToCart(products: Products) {
    this.cartService.addToCart(products)
  }
  selectCategory(e:any){
    this.filter = e.target.value
  }


}

<div className="container">
    <div className="row">
        <div id="head-container">
            <h2 id="heading">Products</h2>
        </div>
        <div class="select-container">
            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" (change)="selectCategory($event)">
                <option selected value="">View All Products</option>
                <option value="Men">Men</option>
                <option value="Women">Women</option>
                <option value="Electronics">Electronics</option>
            </select><br />
        </div>
        <div class="grid-container">
            <div *ngFor="let product of products | filter:filter">
                <div class="col-md-3">
                    <div class="m-2 p-2" id="card">
                        <div class="image-zoom">
                            <img class="product-img" src={{product.url}} />
                        </div>
                        <h5> {{product.Name}} </h5>
                        <p>Price {{product.Price}}</p>
                        <button mat-raised-button color="accent" (click)="addToCart(product)">
                            Add to Cart
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// ReactJS/src/components/Products.js
import React, {useState, useEffect} from "react";
import { collection, addDoc, getDocs, doc } from "firebase/firestore";
// import { firestore } from "../configuration/config";
import './Product.css'
import db from '../configuration/config'
import { onAuthStateChanged } from 'firebase/auth';
import {Navigate} from 'react-router-dom'
import {Button, Alert} from 'react-bootstrap'
import { useDispatch, useSelector } from "react-redux";

// export const controlProducts =[];
function Products(){

    const dispatch =useDispatch();
    const { cartProducts } = useSelector(state=>state.cartReducer)
    const [products, setProducts]=useState([]);

    useEffect(() =>{
        getData();
    }, [])
    
    async function getData(){
     try{
         const users=await getDocs(collection(db, "products"))
         const arrOfProducts=[];
         users.forEach((doc) => {
             const obj = {
             id: doc.id,
             ...doc.data()
            };
            arrOfProducts.push(obj)
        });
        setProducts(arrOfProducts); 
        } catch(error){
            console.log(error);
        }
    }

    const [filterProducts, setFilterProducts]=useState('');
    useEffect(() =>{
        localStorage.setItem('cartProducts', JSON.stringify(cartProducts));
    })
    
    const controlProducts=(products)=>{
        dispatch({type:'addToCart', payload: products})
    }

    return(
        <>

            <div className="container" >
                <div className="row">
                    <div id="head-container">
                        <h2 id="heading">Products</h2>
                    </div>
                    <select  title="Shop By Category" onChange={(e)=>{setFilterProducts(e.target.value)}} value={filterProducts}>
                           <option value="">View All Products</option>
                           <option value="Men">Men</option>
                           <option value="Women">Women</option>
                           <option value="Electronics">Electronics</option>
                    </select ><br />
                    {products.filter((object) => object.Category.includes(filterProducts)).map((products)=>{
                        return <div className="col-md-3"><br />
                            <div className="m-1 p-1" id="card">
                                <img src={products.url} alt="" className="product-img" />
                                <h5>{products.Name}</h5>
                                {/* <h5>{products.Category.Gender}</h5> */}
                                <p><b> ₹{products.Price}</b></p>
                                {/* {isUser ? */}

                                <Button variant="warning" id="to-cart" onClick={()=>{controlProducts(products)}}>
                                        Add to Cart
                                </Button>
                            </div>
                        </div>
                    })}
                </div>
            </div>
        </>

    )
}
export default Products;
